version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./SQL:/app
      - ./SQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    links:
      - mysql